name: CinematicCamera
version: 1.0
main: dev.isa.frqme.cinematicCamera.CinematicCamera
api-version: '1.21'
author: isa
description: Create cinematic camera paths

commands:
  cinematicwand:
    description: Get the cinematic wand
    usage: /cinematicwand
    aliases: [cwand, camwand]

  cinematic:
    description: Manage cinematic paths
    usage: /cinematic <save|delete|list|play|stop|toggle|clear|reload|setspeed>
    aliases: [cam, cinema]

permissions:
  cinematic.*:
    description: Grants all permissions for the CinematicCamera plugin
    children:
      cinematic.admin: true

  cinematic.admin:
    description: Full access to create, edit, and manage cinemantic paths
    default: op
    children:
      cinematic.wand: true
      cinematic.manage: true
      cinematic.play: true
      cinematic.reload: true

  cinematic.wand:
    description: Allows the user to get and use the cinematic wand
    default: op

  cinematic.manage:
    description: Allows creating, deleting, and adding keyframes to paths
    default: op

  cinematic.play:
    description: Allows the user to play a cinematic path
    default: op

  cinematic.reload:
    description: Allows reloading the plugin configuration
    default: op